// backend/seed.mjs
// Generates a COMPLETE, referentially-consistent seed.sql straight from the
// frontend's data.jsx — so the D1 database mirrors exactly what the app shows
// in offline/local mode. Run:
//   node backend/seed.mjs > backend/seed.sql
//   wrangler d1 execute vrp-progress --file=backend/seed.sql
//
// Demo logins it creates (change passwords in production!):
//   teacher/teacher123  parent/parent123  executive/executive123  academic/academic123
//
// Password hashing matches functions/api/_lib.js (PBKDF2, SHA-256, 100k iters,
// "saltHex:hashHex"). Tables are emitted parent-first so foreign keys hold even
// when FK enforcement is on.

import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));

// ---- Pull the real data objects out of ../data.jsx (single source of truth) ----
const dataPath = path.join(here, "..", "data.jsx");
const raw = fs.readFileSync(dataPath, "utf8");
const body = raw.replace(/window\.VRP_DATA[\s\S]*$/, ""); // drop the browser-only export
const VRP = Function(
  `${body}\n return { SUBJECTS, STUDENTS, DATA, PARENT_LINK, PROGRAMS, TEACHERS, CATALOG, COURSE_OFFERINGS, CURRENT_SEMESTER };`
)();
const { SUBJECTS, STUDENTS, DATA, PARENT_LINK, PROGRAMS, TEACHERS, CATALOG, COURSE_OFFERINGS } = VRP;

// ---- helpers ----
function hash(password) {
  const salt = crypto.randomBytes(16);
  const bits = crypto.pbkdf2Sync(password, salt, 100000, 32, "sha256");
  return salt.toString("hex") + ":" + bits.toString("hex");
}
const esc = (s) => String(s).replace(/'/g, "''");
const q = (v) => (v === null || v === undefined ? "NULL" : `'${esc(v)}'`);
const n = (v) => (v === null || v === undefined ? "NULL" : Number(v));

const lines = [];
const out = (sql) => lines.push(sql);
const section = (title) => out(`\n-- ---------- ${title} ----------`);

out("-- Generated by backend/seed.mjs — do not edit by hand.");
out("PRAGMA foreign_keys = ON;");
out("BEGIN TRANSACTION;");

// ---- levels ----
section("levels");
for (const p of Object.values(PROGRAMS)) {
  const years = p.id === "voc" ? 3 : 2;
  out(`INSERT INTO levels (id,code,label,years) VALUES (${q(p.id)},${q(p.code)},${q(p.label)},${years});`);
}

// ---- categories + majors ----
section("categories & majors");
for (const p of Object.values(PROGRAMS)) {
  for (const c of p.categories) {
    out(`INSERT INTO categories (id,level_id,name,color) VALUES (${q(c.id)},${q(p.id)},${q(c.full || c.name)},${q(c.color)});`);
    for (const m of c.majors) {
      out(`INSERT INTO majors (id,category_id,name,short) VALUES (${q(m.id)},${q(c.id)},${q(m.name)},${q(m.short)});`);
    }
  }
}

// ---- teachers (all 12) ----
section("teachers");
for (const t of TEACHERS) {
  out(`INSERT INTO teachers (id,name,spec,email,avatar) VALUES (${q(t.id)},${q(t.name)},${q(t.spec)},${q(t.email)},${n(t.avatar)});`);
}

// ---- courses (curriculum catalog, deduped by code) ----
section("courses");
const seenCourse = new Set();
for (const [majorId, courses] of Object.entries(CATALOG)) {
  for (const c of courses) {
    if (seenCourse.has(c.code)) continue;
    seenCourse.add(c.code);
    out(`INSERT INTO courses (code,name,credits,major_id) VALUES (${q(c.code)},${q(c.name)},${n(c.credits)},${q(majorId)});`);
  }
}

// ---- students (the detailed DBT roster) ----
section("students");
for (const s of STUDENTS) {
  const year = Number((s.classroom.match(/(\d)\//) || [])[1]) || 2;
  out(`INSERT INTO students (id,code,full_name,nickname,major_id,classroom,year,avatar) VALUES (` +
    `${q(s.id)},${q(s.code)},${q(s.fullName)},${q(s.nickname)},${q("hvd-dbt")},${q(s.classroom)},${year},${n(s.avatarSeed)});`);
}

// ---- users (demo accounts) ----
section("users");
const USERS = [
  ["U-teacher", "teacher",   "teacher",   "อ. สิริชัย วงศ์รัตนา",     "T01"],          // teacher -> teachers.id
  ["U-parent",  "parent",    "parent",    "ผู้ปกครองของ " + PARENT_LINK.fullName, PARENT_LINK.id], // parent -> students.id (child)
  ["U-exec",    "executive", "executive", "ดร. วิทวัส สูญยี่ขันธ์",   null],
  ["U-acad",    "academic",  "academic",  "นางสาว ปริญญา ขจรกิตติ",   null],
];
for (const [id, username, role, name, link] of USERS) {
  const pw = hash(username + "123");
  out(`INSERT INTO users (id,username,password_hash,role,display_name,linked_id) VALUES (` +
    `${q(id)},${q(username)},${q(pw)},${q(role)},${q(name)},${link ? q(link) : "NULL"});`);
}

// ---- offerings (all course assignments for the current semester) ----
section("offerings");
for (const o of COURSE_OFFERINGS) {
  out(`INSERT INTO offerings (id,semester,course_code,name,credits,major_id,teacher_id,year,student_grp,schedule,room,capacity) VALUES (` +
    `${q(o.id)},${q(o.semester)},${q(o.code)},${q(o.name)},${n(o.credits)},${q(o.majorId)},${q(o.teacherId)},` +
    `${n(o.year)},${q(o.group)},${q(o.schedule)},${q(o.room)},${n(o.students)});`);
}

// ---- enrollments + attendance (28 students across the 9 DBT subjects) ----
// SUBJECTS[ki] corresponds 1:1 to the ki-th hvd-dbt offering (OF0001..OF0009).
section("enrollments & attendance");
const dbtOfferings = COURSE_OFFERINGS.filter((o) => o.majorId === "hvd-dbt").slice(0, SUBJECTS.length);
let enrSeq = 1;
for (const s of STUDENTS) {
  SUBJECTS.forEach((sub, ki) => {
    const rec = DATA[s.id][sub.id];
    const offering = dbtOfferings[ki];
    const enrId = "EN" + String(enrSeq++).padStart(4, "0");
    const { collected, midterm, final } = rec.scores;
    out(`INSERT INTO enrollments (id,offering_id,student_id,collected,midterm,final,remark) VALUES (` +
      `${q(enrId)},${q(offering.id)},${q(s.id)},${n(collected)},${n(midterm)},${n(final)},${q(rec.remark)});`);

    // one multi-row INSERT for all 16 weeks of attendance
    const cells = rec.attendance
      .map((status, w) => `('AT-${enrId}-${w + 1}',${q(enrId)},${w + 1},${q(status)})`)
      .join(",\n  ");
    out(`INSERT INTO attendance (id,enrollment_id,week,status) VALUES\n  ${cells};`);
  });
}

out("\nCOMMIT;");

// Write to a file argument if given (UTF-8, no BOM — safe on Windows PowerShell
// where `> file` would otherwise emit UTF-16 and corrupt the Thai text);
// otherwise print to stdout for `node seed.mjs > seed.sql` on bash.
const sql = lines.join("\n");
const outFile = process.argv[2];
if (outFile) {
  fs.writeFileSync(outFile, sql, "utf8");
  process.stderr.write(`wrote ${outFile} (${lines.length} statements)\n`);
} else {
  console.log(sql);
}
